server:
  port : 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/db/profiles;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: none
  h2:
    console:
      enabled: true

  servlet.multipart:
    max-file-size: 10MB
    max-request-size: 10MB
